name: Continuous Delivery

on:
  push:
    branches:
      - main  

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Upload dos arquivos do projeto
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado
          path: |
            **/*.py
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Baixar artefato gerado
        uses: actions/download-artifact@v4
        with:
          name: projetozipado

      - name: Listar arquivos baixados
        run: ls -R

  docker:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3


      # - name: Login no Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build da imagem Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest
