name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notificar Discord
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_ALERT_JONNAS }}
          template: "avatar-with-link"
          include-extras: true
