name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint

      - name: Run pylint and save report
        run: |
          pylint . > pylint-report.txt || true

      - name: Upload lint results
        uses: actions/upload-artifact@v3
        with:
          name: pylint-report
          path: pylint-report.txt




