name: Continuous Integration
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Python Lint Code Scanning Action
        uses: advanced-security/python-lint-code-scanning-action@v1.1.1
        with:
          linter: pylint



  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: user/app:latest

  discord:
    runs-on: ubuntu-latest
    needs: [build, docker]
    steps:
      - name: Notificar Discord
        uses: Sniddl/discord-comits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_ALERT_JONNAS }}
          template: "avatar-with-link"
          include-extras: true



